name: tcga_subtype_classification
channels:
  - conda-forge
  - r
  - bioconda
dependencies:
  - python=3.6
  - click
  - Sphinx
  - coverage
  - flake8
  - python-dotenv>=0.5.1
  - jupyter>=1.0.0
  - feather-format
  - numpy
  - pandas
  - scikit-learn
  - umap-learn
  - cmake
  - pip:
    #- git+https://github.com/DmitryUlyanov/Multicore-TSNE#egg=MulticoreTSNE
    - dash==0.21.0
    - dash-core-components==0.21.1
    - dash-html-components==0.9.0
    - dash-renderer==0.12.1
    - dash-table-experiments==0.6.0
  - matplotlib
  - cmocean
  - seaborn
  - plotly
  - flask-compress=1.4.0
  - flask=0.12.2
  - itsdangerous=0.24
  - jinja2=2.10
  - nbformat=4.4.0
  - pytz=2017.3
  - requests=2.18.4
  - urllib3=1.22
  - wcwidth=0.1.7
  - werkzeug=0.14.1
  - r
  - r-caret
  - r-e1071
  - r-randomForest
  - r-party
  - r-gbm
  - r-xtable
  - bioconductor-biobase
